apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-socket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-socket-service
  template:
    metadata:
      labels:
        app: my-socket-service
    spec:
      containers:
        - name: my-socket-service
          image: feedsignalr
          imagePullPolicy: Never
          

---
apiVersion: v1
kind: Service
metadata:
  name: my-socket-service
spec:
  type: LoadBalancer
  selector:
    app: my-socket-service
  ports:
    - port: 45008
      targetPort: 45009
       
   
  