apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-socket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-socket-service
  template:
    metadata:
      labels:
        app: my-socket-service
    spec:
      containers:
        - name: my-socket-service
          image: feedsignalr
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: my-socket-service
spec:
  ports:
    - port: 80                               
      targetPort: 80
  selector:
    name: deployment                    
  type: ClusterIP
  
       
   
  